(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "color-theme-sanityinc-solarized")
(depends-on "cryptol-mode")
(depends-on "haskell-mode")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-descbinds")
(depends-on "helm-projectile")
(depends-on "magit")
(depends-on "projectile")
(depends-on "use-package")
